git:
    depth: 1
os: linux
language: cpp

jobs:
    include:
        - name: "linux"
          os: linux
          dist: bionic
          dist: trusty
          language: cpp
          compiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - gcc-7
                    - g++-7
          before_script:
            - mkdir build
            - cd build
            - cmake .. -DJUST_BUILD=1
          script:
            - export CC=gcc-7
            - export CXX=g++-7
            - make -j 4

        - name: "osx no openmp"
          os: osx
          language: cpp
          compiler: clang
          before_script:
            - mkdir build
            - cd build
            - cmake .. -DJUST_BUILD=1
          script:
            - make -j 4
